"""initial migration

Revision ID: 42f5ed4d6189
Revises: 65e0164f8ba4
Create Date: 2016-08-22 18:16:36.565305

"""

# revision identifiers, used by Alembic.
revision = '42f5ed4d6189'
down_revision = '65e0164f8ba4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tag', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('title', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'tag')
    ### end Alembic commands ###
