"""initial migration

Revision ID: 845f67789f70
Revises: c7052be906e0
Create Date: 2016-08-18 11:15:34.546691

"""

# revision identifiers, used by Alembic.
revision = '845f67789f70'
down_revision = 'c7052be906e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
