"""initial migration

Revision ID: b0e98c9aa78e
Revises: 42f5ed4d6189
Create Date: 2016-08-22 18:55:27.678474

"""

# revision identifiers, used by Alembic.
revision = 'b0e98c9aa78e'
down_revision = '42f5ed4d6189'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'posts', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'blogtype', ['tag_id'], ['id'])
    op.drop_column(u'posts', 'tag')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'posts', sa.Column('tag', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column(u'posts', 'tag_id')
    op.drop_table('blogtype')
    ### end Alembic commands ###
