"""initial migration

Revision ID: c7052be906e0
Revises: 68c64f461780
Create Date: 2016-08-17 22:53:34.098847

"""

# revision identifiers, used by Alembic.
revision = 'c7052be906e0'
down_revision = '68c64f461780'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
